### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by ConnorRigby**

### CODE REVIEW

**Comment by fhunleth** [comment]
I haven't been following closely, but if someone blindly updates to v0.11.0 who's using their own nerves_hub instance, is it possible for them to make a firmware that no longer connects?

**Comment by ConnorRigby** [comment]
> I haven't been following closely, but if someone blindly updates to v0.11.0 who's using their own nerves_hub instance, is it possible for them to make a firmware that no longer connects?

If by blindly, you mean they ignore all the warnings that get printed then yes i think that could happen.

**Comment by fhunleth** [comment]
Is there any reason that the warnings can't be fatal and break builds?

**Comment by jjcarstens** [comment]
If they are connecting to their own instance, then they are either using the `config :nerves_hub_link, ca_certs: ca` option and this will totally fail:
https://github.com/nerves-hub/nerves_hub_link/blob/main/lib/nerves_hub_link/certificate.ex#L29-L47

Or they are using a configurator to supply their own cacerts, in which case it would still connect

**Comment by fhunleth** [comment]
Cool. Thanks!

**Comment by ConnorRigby** [comment]
> Is there any reason that the warnings can't be fatal and break builds?

Jon and I tinkered with this. If there is a situation that can be detected, we raise [here](https://github.com/nerves-hub/nerves_hub_link/pull/83/files#diff-e6adb5a3bf0a85b242d4b77d3100a13fafe420f8f9efdd75fa26ecb2f5cf724cR29)

But we can't detect all situations due to certs being loaded at runtime not compile time

**Review by fhunleth — APPROVED** [review]

**Review by jjcarstens — APPROVED** [review]

**Pull request merged**
